const mongoose = require('mongoose');
const Recipe = require('./models/Recipe');

// MongoDB connection
mongoose.connect('mongodb+srv://leviathan:Josh1987@cluster0.atr55ns.mongodb.net/dishmatch?retryWrites=true&w=majority', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Sample user ID
const userId = '665a426382d4efa558607d00';

// Seed data for recipes
const recipes = [
  {
    name: 'Spaghetti Carbonara',
    cuisine: 'Italian',
    ingredients: ['Spaghetti', 'Eggs', 'Bacon', 'Parmesan Cheese', 'Black Pepper'],
    description: 'A classic Italian pasta dish made with eggs, bacon, and cheese.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/spaghetti_carbonara.jpg',
    creator: userId,
  },
  {
    name: 'Chicken Tikka Masala',
    cuisine: 'Indian',
    ingredients: ['Chicken', 'Tomato Sauce', 'Yogurt', 'Spices'],
    description: 'A popular Indian dish consisting of chicken marinated in spices and served in a creamy tomato sauce.',
    timeToMake: '45 minutes',
    imageUrl: 'https://example.com/chicken_tikka_masala.jpg',
    creator: userId,
  },
  {
    name: 'Sushi Rolls',
    cuisine: 'Japanese',
    ingredients: ['Sushi Rice', 'Nori', 'Fish', 'Vegetables'],
    description: 'Delicious sushi rolls filled with fresh fish and vegetables, wrapped in seaweed and rice.',
    timeToMake: '60 minutes',
    imageUrl: 'https://example.com/sushi_rolls.jpg',
    creator: userId,
  },
  {
    name: 'Tacos al Pastor',
    cuisine: 'Mexican',
    ingredients: ['Pork', 'Pineapple', 'Onion', 'Cilantro', 'Corn Tortillas'],
    description: 'Traditional Mexican tacos made with marinated pork and served with pineapple and onion.',
    timeToMake: '45 minutes',
    imageUrl: 'https://example.com/tacos_al_pastor.jpg',
    creator: userId,
  },
  {
    name: 'Mushroom Risotto',
    cuisine: 'Italian',
    ingredients: ['Arborio Rice', 'Mushrooms', 'Vegetable Broth', 'Parmesan Cheese'],
    description: 'Creamy and flavorful risotto made with Arborio rice, mushrooms, and Parmesan cheese.',
    timeToMake: '40 minutes',
    imageUrl: 'https://example.com/mushroom_risotto.jpg',
    creator: userId,
  },
  {
    name: 'Pad Thai',
    cuisine: 'Thai',
    ingredients: ['Rice Noodles', 'Shrimp', 'Peanuts', 'Eggs', 'Bean Sprouts', 'Tamarind Sauce'],
    description: 'A classic Thai stir-fry dish made with rice noodles, shrimp, peanuts, and bean sprouts.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/pad_thai.jpg',
    creator: userId,
  },
  {
    name: 'Beef Stroganoff',
    cuisine: 'Russian',
    ingredients: ['Beef', 'Mushrooms', 'Onions', 'Sour Cream', 'Beef Broth'],
    description: 'A hearty Russian dish made with tender beef, mushrooms, and onions in a creamy sour cream sauce.',
    timeToMake: '45 minutes',
    imageUrl: 'https://example.com/beef_stroganoff.jpg',
    creator: userId,
  },
  {
    name: 'Chicken Alfredo',
    cuisine: 'Italian',
    ingredients: ['Fettuccine', 'Chicken', 'Heavy Cream', 'Parmesan Cheese', 'Garlic'],
    description: 'A rich and creamy Italian pasta dish made with fettuccine, chicken, and Alfredo sauce.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/chicken_alfredo.jpg',
    creator: userId,
  },
  {
    name: 'Fish Tacos',
    cuisine: 'Mexican',
    ingredients: ['Fish', 'Corn Tortillas', 'Cabbage', 'Avocado', 'Lime'],
    description: 'Crispy fish tacos served with fresh cabbage, avocado, and a squeeze of lime.',
    timeToMake: '25 minutes',
    imageUrl: 'https://example.com/fish_tacos.jpg',
    creator: userId,
  },
  {
    name: 'Margherita Pizza',
    cuisine: 'Italian',
    ingredients: ['Pizza Dough', 'Tomato Sauce', 'Mozzarella Cheese', 'Basil'],
    description: 'A simple and classic Italian pizza topped with tomato sauce, mozzarella cheese, and fresh basil.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/margherita_pizza.jpg',
    creator: userId,
  },
  {
    name: 'Butter Chicken',
    cuisine: 'Indian',
    ingredients: ['Chicken', 'Tomato Sauce', 'Butter', 'Cream', 'Spices'],
    description: 'A rich and creamy Indian dish made with tender chicken in a spiced tomato and butter sauce.',
    timeToMake: '50 minutes',
    imageUrl: 'https://example.com/butter_chicken.jpg',
    creator: userId,
  },
  {
    name: 'Egg Fried Rice',
    cuisine: 'Chinese',
    ingredients: ['Rice', 'Eggs', 'Peas', 'Carrots', 'Soy Sauce'],
    description: 'A quick and easy Chinese dish made with rice, scrambled eggs, and vegetables stir-fried with soy sauce.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/egg_fried_rice.jpg',
    creator: userId,
  },
  {
    name: 'French Onion Soup',
    cuisine: 'French',
    ingredients: ['Onions', 'Beef Broth', 'Gruyère Cheese', 'Baguette'],
    description: 'A classic French soup made with caramelized onions, beef broth, and topped with melted Gruyère cheese.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/french_onion_soup.jpg',
    creator: userId,
  },
  {
    name: 'Shrimp Scampi',
    cuisine: 'Italian',
    ingredients: ['Shrimp', 'Garlic', 'Lemon', 'Butter', 'Parsley'],
    description: 'A delicious Italian seafood dish made with shrimp sautéed in garlic, lemon, and butter sauce.',
    timeToMake: '25 minutes',
    imageUrl: 'https://example.com/shrimp_scampi.jpg',
    creator: userId,
  },
  {
    name: 'Vegetable Stir Fry',
    cuisine: 'Chinese',
    ingredients: ['Broccoli', 'Carrots', 'Bell Peppers', 'Soy Sauce', 'Ginger'],
    description: 'A healthy and flavorful Chinese stir-fry dish made with fresh vegetables and a savory soy-ginger sauce.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/vegetable_stir_fry.jpg',
    creator: userId,
  },
  {
    name: 'Pho',
    cuisine: 'Vietnamese',
    ingredients: ['Rice Noodles', 'Beef', 'Beef Broth', 'Herbs', 'Bean Sprouts'],
    description: 'A traditional Vietnamese soup made with rice noodles, beef, and aromatic herbs in a flavorful broth.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/pho.jpg',
    creator: userId,
  },
  {
    name: 'Peking Duck',
    cuisine: 'Chinese',
    ingredients: ['Duck', 'Hoisin Sauce', 'Cucumbers', 'Green Onions', 'Pancakes'],
    description: 'A famous Chinese dish made with roasted duck, served with hoisin sauce, cucumbers, and green onions.',
    timeToMake: '2 hours',
    imageUrl: 'https://example.com/peking_duck.jpg',
    creator: userId,
  },
  {
    name: 'Pasta Primavera',
    cuisine: 'Italian',
    ingredients: ['Pasta', 'Zucchini', 'Bell Peppers', 'Cherry Tomatoes', 'Parmesan Cheese'],
    description: 'A light and fresh Italian pasta dish made with seasonal vegetables and Parmesan cheese.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/pasta_primavera.jpg',
    creator: userId,
  },
  {
    name: 'Beef Tacos',
    cuisine: 'Mexican',
    ingredients: ['Beef', 'Corn Tortillas', 'Cheese', 'Lettuce', 'Tomatoes'],
    description: 'Tasty Mexican tacos filled with seasoned beef, cheese, lettuce, and tomatoes.',
    timeToMake: '25 minutes',
    imageUrl: 'https://example.com/beef_tacos.jpg',
    creator: userId,
  },
  {
    name: 'Clam Chowder',
    cuisine: 'American',
    ingredients: ['Clams', 'Potatoes', 'Onions', 'Celery', 'Cream'],
    description: 'A creamy and hearty American soup made with clams, potatoes, and onions.',
    timeToMake: '45 minutes',
    imageUrl: 'https://example.com/clam_chowder.jpg',
    creator: userId,
  },
  {
    name: 'Pulled Pork Sandwich',
    cuisine: 'American',
    ingredients: ['Pork Shoulder', 'BBQ Sauce', 'Coleslaw', 'Buns'],
    description: 'Tender pulled pork served in a sandwich with BBQ sauce and coleslaw.',
    timeToMake: '8 hours',
    imageUrl: 'https://example.com/pulled_pork_sandwich.jpg',
    creator: userId,
  },
  {
    name: 'Gazpacho',
    cuisine: 'Spanish',
    ingredients: ['Tomatoes', 'Cucumber', 'Bell Pepper', 'Onion', 'Garlic'],
    description: 'A cold Spanish soup made with tomatoes and vegetables.',
    timeToMake: '15 minutes',
    imageUrl: 'https://example.com/gazpacho.jpg',
    creator: userId,
  },
  {
    name: 'Falafel Wrap',
    cuisine: 'Middle Eastern',
    ingredients: ['Chickpeas', 'Tahini', 'Cucumber', 'Tomato', 'Pita Bread'],
    description: 'Crispy falafel served in a wrap with tahini sauce and fresh vegetables.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/falafel_wrap.jpg',
    creator: userId,
  },
  {
    name: 'Beef Wellington',
    cuisine: 'British',
    ingredients: ['Beef Tenderloin', 'Puff Pastry', 'Mushrooms', 'Prosciutto'],
    description: 'A classic British dish of beef wrapped in puff pastry and baked.',
    timeToMake: '2 hours',
    imageUrl: 'https://example.com/beef_wellington.jpg',
    creator: userId,
  },
  {
    name: 'Pad See Ew',
    cuisine: 'Thai',
    ingredients: ['Wide Rice Noodles', 'Broccoli', 'Eggs', 'Soy Sauce'],
    description: 'A popular Thai stir-fry dish made with wide rice noodles and vegetables.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/pad_see_ew.jpg',
    creator: userId,
  },
  {
    name: 'Baklava',
    cuisine: 'Turkish',
    ingredients: ['Phyllo Dough', 'Walnuts', 'Honey', 'Cinnamon'],
    description: 'A sweet Turkish pastry made with layers of phyllo dough and nuts, soaked in honey.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/baklava.jpg',
    creator: userId,
  },
  {
    name: 'Shrimp Tacos',
    cuisine: 'Mexican',
    ingredients: ['Shrimp', 'Corn Tortillas', 'Cabbage', 'Avocado', 'Lime'],
    description: 'Delicious tacos filled with seasoned shrimp and fresh toppings.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/shrimp_tacos.jpg',
    creator: userId,
  },
  {
    name: 'Tom Yum Soup',
    cuisine: 'Thai',
    ingredients: ['Shrimp', 'Lemongrass', 'Galangal', 'Lime Leaves', 'Chilies'],
    description: 'A spicy and sour Thai soup made with shrimp and aromatic herbs.',
    timeToMake: '40 minutes',
    imageUrl: 'https://example.com/tom_yum_soup.jpg',
    creator: userId,
  },
  {
    name: 'Goulash',
    cuisine: 'Hungarian',
    ingredients: ['Beef', 'Paprika', 'Onions', 'Bell Peppers', 'Tomatoes'],
    description: 'A hearty Hungarian stew made with beef and vegetables, flavored with paprika.',
    timeToMake: '1.5 hours',
    imageUrl: 'https://example.com/goulash.jpg',
    creator: userId,
  },
  {
    name: 'Caesar Salad',
    cuisine: 'Italian',
    ingredients: ['Romaine Lettuce', 'Croutons', 'Parmesan Cheese', 'Caesar Dressing'],
    description: 'A classic Italian salad made with fresh romaine lettuce and a creamy Caesar dressing.',
    timeToMake: '15 minutes',
    imageUrl: 'https://example.com/caesar_salad.jpg',
    creator: userId,
  },
  {
    name: 'Bibimbap',
    cuisine: 'Korean',
    ingredients: ['Rice', 'Vegetables', 'Egg', 'Gochujang', 'Beef'],
    description: 'A popular Korean rice dish topped with assorted vegetables, beef, and a fried egg.',
    timeToMake: '30 minutes',
    imageUrl: 'https://example.com/bibimbap.jpg',
    creator: userId,
  },
  {
    name: 'Moussaka',
    cuisine: 'Greek',
    ingredients: ['Eggplant', 'Ground Beef', 'Tomatoes', 'Béchamel Sauce'],
    description: 'A layered Greek casserole made with eggplant, ground beef, and béchamel sauce.',
    timeToMake: '1.5 hours',
    imageUrl: 'https://example.com/moussaka.jpg',
    creator: userId,
  },
  {
    name: 'Ceviche',
    cuisine: 'Peruvian',
    ingredients: ['Fish', 'Lime Juice', 'Onions', 'Cilantro', 'Chilies'],
    description: 'A fresh and tangy Peruvian dish made with raw fish marinated in lime juice.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/ceviche.jpg',
    creator: userId,
  },
  {
    name: 'Katsu Curry',
    cuisine: 'Japanese',
    ingredients: ['Pork Cutlet', 'Curry Sauce', 'Rice', 'Vegetables'],
    description: 'A Japanese dish consisting of a breaded pork cutlet served with curry sauce and rice.',
    timeToMake: '45 minutes',
    imageUrl: 'https://example.com/katsu_curry.jpg',
    creator: userId,
  },
  {
    name: 'Jambalaya',
    cuisine: 'Cajun',
    ingredients: ['Chicken', 'Sausage', 'Shrimp', 'Rice', 'Bell Peppers', 'Cajun Spices'],
    description: 'A flavorful Cajun dish made with a mix of meats, rice, and vegetables.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/jambalaya.jpg',
    creator: userId,
  },
  {
    name: 'Biryani',
    cuisine: 'Indian',
    ingredients: ['Rice', 'Chicken', 'Yogurt', 'Spices', 'Fried Onions'],
    description: 'A fragrant Indian rice dish made with spices, chicken, and fried onions.',
    timeToMake: '1.5 hours',
    imageUrl: 'https://example.com/biryani.jpg',
    creator: userId,
  },
  {
    name: 'Ratatouille',
    cuisine: 'French',
    ingredients: ['Eggplant', 'Zucchini', 'Tomatoes', 'Bell Peppers', 'Herbs de Provence'],
    description: 'A classic French vegetable stew made with a variety of fresh vegetables and herbs.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/ratatouille.jpg',
    creator: userId,
  },
  {
    name: 'Croque Monsieur',
    cuisine: 'French',
    ingredients: ['Bread', 'Ham', 'Gruyère Cheese', 'Béchamel Sauce'],
    description: 'A traditional French grilled ham and cheese sandwich topped with béchamel sauce.',
    timeToMake: '20 minutes',
    imageUrl: 'https://example.com/croque_monsieur.jpg',
    creator: userId,
  },
  {
    name: 'Empanadas',
    cuisine: 'Argentinian',
    ingredients: ['Ground Beef', 'Onions', 'Olives', 'Raisins', 'Dough'],
    description: 'Savory pastries filled with a mixture of ground beef, onions, olives, and raisins.',
    timeToMake: '1 hour',
    imageUrl: 'https://example.com/empanadas.jpg',
    creator: userId,
  },
  {
    name: 'Gumbo',
    cuisine: 'Cajun',
    ingredients: ['Chicken', 'Sausage', 'Okra', 'Rice', 'Bell Peppers', 'Cajun Spices'],
    description: 'A hearty Cajun stew made with chicken, sausage, okra, and spices served over rice.',
    timeToMake: '1.5 hours',
    imageUrl: 'https://example.com/gumbo.jpg',
    creator: userId,
  },
];

// Function to seed data to the database
async function seedData() {
  try {
    // Clear existing data
    await Recipe.deleteMany({});
    console.log('Previous data erased.');

    // Insert recipes into the database
    await Recipe.insertMany(recipes);
    console.log('Seed data inserted successfully.');
  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    // Close the database connection
    mongoose.disconnect();
  }
}

// Call the function to seed the data
seedData();
